version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-hello-world_server_1
      APP_PORT: 3000
    
  server:
    image: getumbrel/community-app-store-hello-world:latest
    user: "1000:1000"
    init: true

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.28.3
    restart: unless-stopped
    volumes:
      - .zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 6914:8080
    environment:
      - TZ=Europe/Amsterdam
      - APP_URL=http://umbrel.local:6914
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyACM0:/dev/ttyACM0
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s

volumes:
  zigbee2mqtt:

