version: "3.9"
services:
  vlc:
    image: ghcr.io/aperim/vlc-player-rpi:latest
    restart: unless-stopped
    network_mode: host
    mem_limit: 1gb
    privileged: true
    environment:
      - VLC_SOURCE_URL=rtp://@234.0.1.255:1234
      - VLC_ZOOM=1.5
    volumes:
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
    devices:
      - "/dev/tty0:/dev/tty0"
      - "/dev/tty2:/dev/tty2"
      - "/dev/fb0:/dev/fb0"
      - "/dev/input:/dev/input"
      - "/dev/snd:/dev/snd"